id: I657A02E4
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3875final
source_file: null
initial_creation_type: input
imported: '2022-07-27T11:37:54.638189'
last_modified: '2022-07-27T11:37:54.638205'
parser: null
source_metadata:
  title: commentary
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
